### ISSUE TITLE
NullPointerException for DeltaSol BS 2009

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#23]
on reading field Systemtime with PacketFieldValue.formatText() a NullPointerExpection occurs, as the locale = null in Sepecification.createUtcDateFormat():77:
```
java.lang.NullPointerException
	at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:617)
	at de.resol.vbus.Specification.createUtcDateFormat(Specification.java:77)
	at de.resol.vbus.Specification.access$000(Specification.java:58)
	at de.resol.vbus.Specification$Formatter$2.formatTextValue(Specification.java:145)
	at de.resol.vbus.Specification.formatTextValueFromRawValueInternal(Specification.java:723)
	at de.resol.vbus.Specification.formatTextValueFromRawValue(Specification.java:738)
	at de.resol.vbus.Specification.formatTextValueFromRawValue(Specification.java:754)
	at de.resol.vbus.Specification$PacketFieldValue.formatTextValue(Specification.java:485)
	at de.resol.vbus.Specification$PacketFieldValue.formatText(Specification.java:505)
	at de.resol.vbus.Specification$PacketFieldValue.formatText(Specification.java:511)
```

I propose to fix it with:
`			return formatText(null, Locale.getDefault(), Language.En);`
in Specification.formatText() instead of
`			return formatText(null, null, Language.En);`

**Comment by danielwippermann** [comment]
Thank you @ramack! The fix is committed in f1684f529e780149c4254bb67bd688d616488615 and version 0.8.0 should appear in the Maven repo shortly.
